mkdir -p /tmp/default_paths_for_docker/etc/httpd
mkdir -p /tmp/default_paths_for_docker/etc/nginx
mkdir -p /tmp/default_paths_for_docker/etc/opt/rh/rh-php71
mkdir -p /tmp/default_paths_for_docker/etc/php-fpm.d
mkdir -p /tmp/default_paths_for_docker/home
mkdir -p /tmp/default_paths_for_docker/root
mkdir -p /tmp/default_paths_for_docker/var/log
mkdir -p /tmp/default_paths_for_docker/var/www
mkdir -p /tmp/default_paths_for_docker/var/opt
